export { default as Status } from "./Status";
export { default as Chat } from "./Chat";
export { default as Menu } from "./Menu";
export { default as Back } from "./Back";
export { default as Search } from "./Search";
export { default as Clip } from "./Clip";
export { default as Smiley } from "./Smiley";
export { default as Ptt } from "./Ptt";
// export { default as X } from "./X";
// export { default as Sticker } from "./Sticker";
// export { default as Gif } from "./Gif";
export { default as TailIn } from "./TailIn";
export { default as TailOut } from "./TailOut";
export { default as MessageCheck } from "./MessageCheck";
export { default as Photo } from "./Photo";
// export { default as Alert } from "./Alert";
